/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAnimalsIndexRouteImport } from './routes/_authenticated/animals.index'
import { Route as AuthenticatedAnimalsIdRouteImport } from './routes/_authenticated/animals.$id'
import { Route as AuthenticatedBarnsIndexRouteImport } from './routes/_authenticated/barns.index'
import { Route as AuthenticatedBarnsIdRouteImport } from './routes/_authenticated/barns.$id'
import { Route as AuthenticatedCustomersIndexRouteImport } from './routes/_authenticated/customers.index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAnimalsIndexRoute =
  AuthenticatedAnimalsIndexRouteImport.update({
    id: '/animals/',
    path: '/animals/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAnimalsIdRoute = AuthenticatedAnimalsIdRouteImport.update({
  id: '/animals/$id',
  path: '/animals/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBarnsIndexRoute = AuthenticatedBarnsIndexRouteImport.update({
  id: '/barns/',
  path: '/barns/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBarnsIdRoute = AuthenticatedBarnsIdRouteImport.update({
  id: '/barns/$id',
  path: '/barns/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCustomersIndexRoute =
  AuthenticatedCustomersIndexRouteImport.update({
    id: '/customers/',
    path: '/customers/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/animals/$id': typeof AuthenticatedAnimalsIdRoute
  '/barns/$id': typeof AuthenticatedBarnsIdRoute
  '/animals/': typeof AuthenticatedAnimalsIndexRoute
  '/barns/': typeof AuthenticatedBarnsIndexRoute
  '/customers/': typeof AuthenticatedCustomersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/animals/$id': typeof AuthenticatedAnimalsIdRoute
  '/barns/$id': typeof AuthenticatedBarnsIdRoute
  '/animals': typeof AuthenticatedAnimalsIndexRoute
  '/barns': typeof AuthenticatedBarnsIndexRoute
  '/customers': typeof AuthenticatedCustomersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/animals/$id': typeof AuthenticatedAnimalsIdRoute
  '/_authenticated/barns/$id': typeof AuthenticatedBarnsIdRoute
  '/_authenticated/animals/': typeof AuthenticatedAnimalsIndexRoute
  '/_authenticated/barns/': typeof AuthenticatedBarnsIndexRoute
  '/_authenticated/customers/': typeof AuthenticatedCustomersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/animals/$id'
    | '/barns/$id'
    | '/animals/'
    | '/barns/'
    | '/customers/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/animals/$id'
    | '/barns/$id'
    | '/animals'
    | '/barns'
    | '/customers'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/dashboard'
    | '/_authenticated/animals/$id'
    | '/_authenticated/barns/$id'
    | '/_authenticated/animals/'
    | '/_authenticated/barns/'
    | '/_authenticated/customers/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/animals/': {
      id: '/_authenticated/animals/'
      path: '/animals'
      fullPath: '/animals/'
      preLoaderRoute: typeof AuthenticatedAnimalsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/animals/$id': {
      id: '/_authenticated/animals/$id'
      path: '/animals/$id'
      fullPath: '/animals/$id'
      preLoaderRoute: typeof AuthenticatedAnimalsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/barns/': {
      id: '/_authenticated/barns/'
      path: '/barns'
      fullPath: '/barns/'
      preLoaderRoute: typeof AuthenticatedBarnsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/barns/$id': {
      id: '/_authenticated/barns/$id'
      path: '/barns/$id'
      fullPath: '/barns/$id'
      preLoaderRoute: typeof AuthenticatedBarnsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/customers/': {
      id: '/_authenticated/customers/'
      path: '/customers'
      fullPath: '/customers/'
      preLoaderRoute: typeof AuthenticatedCustomersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedAnimalsIdRoute: typeof AuthenticatedAnimalsIdRoute
  AuthenticatedBarnsIdRoute: typeof AuthenticatedBarnsIdRoute
  AuthenticatedAnimalsIndexRoute: typeof AuthenticatedAnimalsIndexRoute
  AuthenticatedBarnsIndexRoute: typeof AuthenticatedBarnsIndexRoute
  AuthenticatedCustomersIndexRoute: typeof AuthenticatedCustomersIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedAnimalsIdRoute: AuthenticatedAnimalsIdRoute,
  AuthenticatedBarnsIdRoute: AuthenticatedBarnsIdRoute,
  AuthenticatedAnimalsIndexRoute: AuthenticatedAnimalsIndexRoute,
  AuthenticatedBarnsIndexRoute: AuthenticatedBarnsIndexRoute,
  AuthenticatedCustomersIndexRoute: AuthenticatedCustomersIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
